name: CI Example

on:
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Node 설치
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 패키지 설치
        run: npm install

      - name: Docker 이미지 빌드
        run: docker build -t test-image .
